function results = emptyCvResultStruct(nRows)
%EMPTYCVRESULTSTRUCT Create the CV/GLM result struct with stable fields.

template = struct( ...
    'name', [], ...
    'sparseness', [], ...
    'frame', [], ...
    'loglikelihood', [], ...
    'receptive_field_type', [], ...
    'AIC', [], ...
    'BIC', [], ...
    'params', [], ...
    'reFireRate', [], ...
    'pvalue', [], ...
    'cvLogLikelihood', [], ...
    'cvLogLikelihoodPerFrame', [], ...
    'naiveCvLogLikelihood', [], ...
    'cvDeltaLogLikelihood', [], ...
    'foldLogLikelihood', [], ...
    'foldNaiveLogLikelihood', [], ...
    'foldTrainLogLikelihood', [], ...
    'foldParams', [], ...
    'foldAlpha', [], ...
    'foldOffset', [], ...
    'foldCalibrationMethod', [], ...
    'calibration', [], ...
    'numClosest', [], ...
    'fullFitParams', [], ...
    'fullFitAlpha', [], ...
    'fullFitOffset', []);

results = repmat(template, nRows, 1);
end
