function [shapeParams, fval] = fitRfShapeOnTrain(Egorelative_closest, fired, ...
    trainIdx, receptive_field_type, calibration, fitOptions)
%FITRFSHAPEONTRAIN Fit RF shape parameters with profiled GLM calibration.

if nargin < 6 || isempty(fitOptions)
    fitOptions = struct();
end

spec = getRfSpec(receptive_field_type);
nParams = spec.nParams;

objFun = @(p) scoreRfCv(p, Egorelative_closest, fired, trainIdx, [], ...
    receptive_field_type, calibration);

hybridopts = optimoptions('fmincon', ...
    'Algorithm', 'interior-point', ...
    'Display', 'none', ...
    'FiniteDifferenceType', 'central', ...
    'FiniteDifferenceStepSize', getOption(fitOptions, 'FiniteDifferenceStepSize', 1e-4), ...
    'MaxIterations', getOption(fitOptions, 'HybridMaxIterations', 5e3), ...
    'MaxFunctionEvaluations', getOption(fitOptions, 'HybridMaxFunctionEvaluations', 5e4));

popSize = getOption(fitOptions, 'PopulationSize', max(400, 40 * nParams));
eliteCnt = getOption(fitOptions, 'EliteCount', ceil(0.05 * popSize));

options = optimoptions('ga', ...
    'UseParallel', getOption(fitOptions, 'UseParallel', true), ...
    'PopulationSize', popSize, ...
    'EliteCount', eliteCnt, ...
    'CrossoverFraction', getOption(fitOptions, 'CrossoverFraction', 0.8), ...
    'MutationFcn', {@mutationadaptfeasible}, ...
    'InitialPopulationRange', [spec.lb; spec.ub], ...
    'MaxGenerations', getOption(fitOptions, 'MaxGenerations', 150), ...
    'FunctionTolerance', getOption(fitOptions, 'FunctionTolerance', 1e-6), ...
    'MaxStallGenerations', getOption(fitOptions, 'MaxStallGenerations', 40), ...
    'Display', getOption(fitOptions, 'Display', 'off'), ...
    'HybridFcn', {@fmincon, hybridopts}, ...
    'OutputFcn', @myOutputFcn);

[shapeParams, fval] = ga(objFun, nParams, spec.A, spec.b, [], [], ...
    spec.lb, spec.ub, [], options);
end

function value = getOption(options, name, defaultValue)
if isstruct(options) && isfield(options, name) && ~isempty(options.(name))
    value = options.(name);
else
    value = defaultValue;
end
end

function [state, options, optchanged] = myOutputFcn(options, state, ~)
[bestScore, bestIdx] = min(state.Score);
bestParam = state.Population(bestIdx, :);

if mod(state.Generation, 10) == 0
    fprintf('Generation %d: ', state.Generation);
    fprintf('Best shape params = [');
    fprintf('%.4f ', bestParam);
    fprintf(']  Score = %.4f\n', bestScore);
end

optchanged = false;
end
